version: '3'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    env_file:
      - .env
    ports:
      - "3306:3306"
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge