version: '3'

services:
  mysql:
    image: mysql:5.6
    container_name: docker-mysql
    environment:
      MYSQL_DATABASE: amsguitars
      MYSQL_USER: amsguitars
      MYSQL_PASSWORD: ams123guitars%
      MYSQL_ROOT_PASSWORD: ams123guitars%%%
    ports:
      - "3306:3306"
    restart: always

  web:
    image: php:7.3-apache
    container_name: docker-php
    ports:
      - "80:80"
    volumes:
      - ./www:/var/www/html
    links:
      - mysql
